name: List Repository Structure

on:
  workflow_dispatch:

jobs:
  list-structure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List files and directories
      run: |
        echo "Repository structure:"
        tree -L 3
        
