name: Build and Test APK

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip openjdk-11-jdk unzip wget git

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install buildozer cython kivy pytest

    - name: Run tests with pytest
      run: |
        pytest

    - name: Build APK with Buildozer
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: WebRadioPy-APK
        path: bin/*.apk
